language: node_js

node_js:
    - "0.10"

before_install:
    - "export DISPLAY=:99.0"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"

before_script:
    - npm install mozilla-download -g
    - cd ..
    - mozilla-download --branch latest -c release firefox
    - cd $TRAVIS_BUILD_DIR
    - export FIREFOX_BIN==$TRAVIS_BUILD_DIR/../firefox/firefox
    - git submodule update --init
    - cd addon-sdk
    - . bin/activate
    - cd ../
    - $FIREFOX_BIN -v

script: cfx test -b $FIREFOX_BIN
